/*
 * File: app/view/acces.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hola.view.acces', {
    extend: 'Ext.navigation.View',
    alias: 'widget.acces',

    config: {
        id: 'acces',
        layout: {
            animation: 'pop',
            type: 'card'
        },
        items: [
            {
                xtype: 'formpanel',
                id: 'frmAcces',
                itemId: 'frmAcces',
                padding: 15,
                ui: '',
                title: 'Registre d\'accés',
                items: [
                    {
                        xtype: 'label',
                        html: '<center><h2>Gestió dels processos de treball</h2></center><br/>',
                        itemId: 'etiqueta'
                    },
                    {
                        xtype: 'textfield',
                        id: 'usuari',
                        itemId: 'usuari',
                        label: 'Usuari:',
                        name: 'usuari',
                        required: true
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'clau',
                        label: 'Clau:',
                        name: 'clau',
                        required: true
                    },
                    {
                        xtype: 'label',
                        html: '<br/><hr/><center>Benvingut</center><br/>'
                    },
                    {
                        xtype: 'button',
                        id: 'acces',
                        itemId: 'mybutton',
                        ui: 'forward',
                        text: 'Accedir'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'amaga',
                event: 'hide',
                delegate: '#acces'
            },
            {
                fn: 'onAccesInitialize',
                event: 'initialize',
                delegate: '#acces'
            }
        ]
    },

    amaga: function(component, options) {
        component='frmAcces'
    },

    onAccesInitialize: function(component, options) {
        component='usuariPanel'
    }

});