/*
 * File: app/view/detailPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.view.detailPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.detailpanel',

    config: {
        id: 'detailPanel',
        itemId: 'detailPanel',
        ui: '',
        layout: {
            type: 'card'
        },
        tpl: [
            '</br>',
            '<b>Nom:</b> {nom}</br>',
            '<b>Descripció:</b> {descripcio}'
        ]
    }

});