/*
 * File: app/view/loginForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.view.loginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginform',

    config: {
        padding: 15,
        ui: '',
        layout: {
            pack: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Processos de treball'
            },
            {
                xtype: 'label',
                html: '<center><h2>Gestió dels processos de treball</h2></center><br/>',
                itemId: 'etiqueta0'
            },
            {
                xtype: 'label',
                itemId: 'etiqueta1'
            },
            {
                xtype: 'fieldset',
                title: 'Dades de registre:',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Usuari:',
                        name: 'username',
                        required: true,
                        placeHolder: 'Nom d\'usuari'
                    },
                    {
                        xtype: 'passwordfield',
                        label: 'Clau:',
                        name: 'password',
                        required: true,
                        placeHolder: 'Clau d\'usuari'
                    }
                ]
            },
            {
                xtype: 'label',
                html: '<br/><hr/><center>Benvingut</center><br/>',
                itemId: 'etiqueta2'
            },
            {
                xtype: 'button',
                itemId: 'login',
                ui: 'forward',
                iconCls: 'action',
                iconMask: true,
                text: 'Accedir'
            }
        ],
        listeners: [
            {
                fn: 'onLoginTap',
                event: 'tap',
                delegate: '#login'
            }
        ]
    },

    onLoginTap: function(button, e, options) {
        button.up('formpanel').down('#etiqueta1').setHtml("");
        var top = button.up('viewport');

        /*
        PFC.username = button.up('formpanel').getValues().username;


        if (PFC.username!==""){
        top.down('#loggedInUserName').setHtml(PFC.username);
        top.setActiveItem(1);
        }else{
        button.up('formpanel').down('#etiqueta1').setHtml("<DIV style='color:red'>Necessita omplenar les dades de usuari.</div>");
        }
        */




        /*
        if (PFC.store.usuariJson.filter("usernameFilter",button.up('formpanel').getValues().username).anyMatch){
        alert ("Trobat");
        }else{
        alert ("NO Trobat");
        }
        */
        /*
        if (PFC.store.usuariJson.comprovaUsuari(button.up('formpanel').getValues().username)){
        alert ("trobat");
        }else{
        alert ("NO trobat");
        }
        */

        var x = PFC.store.usuariJson.find("username",button.up('formpanel').getValues().username);
        alert (x);
    }

});