/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hola.view.MyNavigationView', {
    extend: 'Ext.navigation.View',

    config: {
        items: [
            {
                xtype: 'panel',
                html: '<hr/><center>Benvingut</center>',
                id: 'mypanel',
                layout: {
                    type: 'vbox'
                },
                title: 'Registre d\'accés',
                background: 'logo.jpg',
                items: [
                    {
                        xtype: 'label',
                        cls: [
                            ''
                        ],
                        html: '<center><h2>Gestió dels processos de treball</h2></center>',
                        itemId: 'etiqueta'
                    },
                    {
                        xtype: 'textfield',
                        id: 'usuari',
                        label: 'Usuari:'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'clau',
                        label: 'Clau:'
                    },
                    {
                        xtype: 'button',
                        id: 'acces',
                        text: 'Accedir'
                    }
                ]
            }
        ]
    }

});