/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hola.view.MyNavigationView', {
    extend: 'Ext.navigation.View',

    config: {
        items: [
            {
                xtype: 'panel',
                html: '<br/><hr/><center>Benvingut</center>',
                id: 'mypanel',
                title: 'Registre d\'accés',
                background: 'logo.jpg',
                items: [
                    {
                        xtype: 'container',
                        padding: 15,
                        items: [
                            {
                                xtype: 'label',
                                html: '<center><h2>Gestió dels processos de treball</h2></center><br/>',
                                itemId: 'etiqueta'
                            },
                            {
                                xtype: 'textfield',
                                id: 'usuari',
                                itemId: 'usuari',
                                label: 'Usuari:',
                                name: 'usuari',
                                required: true
                            },
                            {
                                xtype: 'passwordfield',
                                id: 'clau',
                                label: 'Clau:',
                                name: 'clau',
                                required: true
                            },
                            {
                                xtype: 'button',
                                docked: 'bottom',
                                id: 'acces',
                                itemId: 'mybutton',
                                ui: 'forward',
                                text: 'Accedir'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onAccesLeftChange',
                event: 'leftchange',
                delegate: '#acces'
            }
        ]
    },

    onAccesLeftChange: function(component, value, oldValue, options) {

    }

});