/*
 * File: app/view/addProcesForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.view.addProcesForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.addprocesform',

    config: {
        itemId: 'addProcesForm',
        layout: {
            pack: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'fieldset',
                id: 'formulariProces',
                title: 'Afegir un nou procés',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Nom',
                        name: 'nom',
                        required: true
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Descripció',
                        name: 'descripcio'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'submit',
                ui: 'confirm-round',
                iconCls: 'add',
                iconMask: true,
                text: 'Crea'
            }
        ],
        listeners: [
            {
                fn: 'onSubmitTap',
                event: 'tap',
                delegate: '#submit'
            },
            {
                fn: 'onAddProcesFormInitialize',
                event: 'initialize'
            }
        ]
    },

    onSubmitTap: function(button, e, options) {
        var form = button.up('addprocesform'),
        mainPanel = form.up('#mainPanel'),
        store = mainPanel.down('#procesosList').getStore(),
        //ts = new Date(),
        procesRecord = form.getValues();

        //Store to local storage and sync to remote syncstorage
        store.add(procesRecord);
        //----store.sync();

        //Associem el nou procés a les etiquetes seleccionades
        //var tAssociat = Ext.getStore('associatJson');


        form.reset();
        Ext.getCmp('procesosList').deselectAll();

        Ext.getCmp('mainPanel').animateTo('right');
        Ext.getCmp('listPanel').setHidden(false);
        Ext.getCmp('usuariPanel').setHidden(false);
        Ext.getCmp('torna').setHidden(true);
        PFC.titol = "Processos de treball";
        Ext.getCmp('loggedInUserName').setTitle(PFC.titol);

        Ext.getCmp('finestra').removeAt(2);




    },

    onAddProcesFormInitialize: function(component, options) {
        //Cerquem les diferents etiquetes 
        var myPanel = Ext.create('Ext.Label', {html: '<br/>Etiquetes:<hr/>', style:'background-color:#FFEFD5'});
        Ext.getCmp('formulariProces').add([myPanel]);


        var tEtiqueta = Ext.getStore('etiquetaJson');
        var tTipusEtiqueta = Ext.getStore('etiquetaTipusJson');

        var aux = 0;
        for (i===0;i<tTipusEtiqueta.getCount();i++){
            if (i==aux){
                var etiquetaV = Ext.create('Ext.Label', {html: tTipusEtiqueta.getAt(i).get('nom'),style:'background-color:#FFEFD5'});
                Ext.getCmp('formulariProces').add([etiquetaV]);

                //Filtrem els tipus d'etiqueta

                tEtiqueta.filter('etiquetaTipus_id',tTipusEtiqueta.getAt(i).get('id'));

                var j=0;
                for (j===0;j<tEtiqueta.getCount();j++){
                    var etiquetaV2 = Ext.create('Ext.field.Checkbox', {
                        xtype: 'checkboxfield',
                        label: tEtiqueta.getAt(j).get('nom'),
                        labelWrap:true,
                        id:"Etiqueta_"+tTipusEtiqueta.getAt(i).get('id')+"_"+tEtiqueta.getAt(j).get('id'),
                        value:tEtiqueta.getAt(j).get('id')
                    });
                    Ext.getCmp('formulariProces').add([etiquetaV2]);

                }
                //Esborrem el filtre per a que continui creant checkbox
                tEtiqueta.clearFilter();
            }
            aux=aux+1;
        }

    }

});