/*
 * File: app/view/Picture.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.view.Picture', {
    extend: 'Ext.Container',

    config: {
        id: 'Picture',
        itemId: 'Picture',
        minHeight: 100,
        style: 'overflow: hidden;background-color:#FFEFD5;',
        ui: '',
        layout: {
            align: 'start',
            type: 'vbox'
        },
        overflow: 'hidden',
        tpl: [
            ''
        ],
        items: [
            {
                xtype: 'container',
                id: 'pictureDetall',
                tpl: [
                    '<div>{descripcio}</div>',
                    '<!-- ',
                    '<div><img src="{picture}" width="160" /></div>',
                    '-->'
                ],
                flex: 0
            },
            {
                xtype: 'container',
                ui: '',
                flex: 0,
                items: [
                    {
                        xtype: 'image',
                        height: 200,
                        id: 'imatgeInstruccio',
                        ui: '',
                        width: 200,
                        src: 'touch/resources/images/logo.png'
                    }
                ]
            },
            {
                xtype: 'component',
                html: '',
                id: 'componente',
                itemId: 'componente',
                tpl: [
                    ''
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                hidden: true,
                id: 'barraSubinstruccio',
                items: [
                    {
                        xtype: 'button',
                        bottom: 5,
                        hidden: true,
                        itemId: 'mybutton',
                        right: 5,
                        iconCls: 'add',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        id: 'borraInstruccio',
                        ui: 'decline-round',
                        iconCls: 'delete',
                        iconMask: true,
                        text: 'Esborra Instrucció',
                        flex: 1
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#mybutton'
            },
            {
                fn: 'onBorraInstruccioTap',
                event: 'tap',
                delegate: '#borraInstruccio'
            }
        ]
    },

    onMybuttonTap: function(button, e, options) {
        /*
        Ext.device.Camera.capture({
        source: 'camera',
        destination: 'file',

        success: function(url) {
        //show the newly captured image in a full screen Ext.Img component:
        Ext.create('Ext.Img', {
            src: url,
            fullscreen: true
        });
    }
        });


        Ext.device.Camera.capture({
    source: 'camera',
    destination: 'file',

    success: function(url) {
        this.fireEvent('change', this, url);
    },
    failure: function() {
        Ext.Msg.alert('Error', 'There was an error when acquiring the picture.');
    },
    scope: this
        });
        */


        Ext.device.Camera.capture({
    success: function(url) {
        Ext.getCmp('imatgeInstruccio').setSrc(url);
    },
    scope: this,
    source: 'camera',
    destination: 'file'
        });


    },

    onBorraInstruccioTap: function(button, e, options) {
        Ext.Msg.confirm(
        "Confirmació d'esborrat de Instrucció", "Esteu segurs que voleu esborrar aquesta instrucció?", 
        function ( answer ) { 
            if ( answer == 'yes') {           
                //Esborrem la instrucció del JSON
                Ext.getStore('instruccioJson').removeAt(Ext.getStore('instruccioJson').find('id',PFC.instruccio)); 

                PFC.titol=PFC.titolAux;
                Ext.getCmp('detailPanel').setHidden(false);
                Ext.getCmp('finestra').remove(Ext.getCmp('Picture'),true);
                PFC.instruccio=-1;
            } 
        }
        );
    }

});