/*
 * File: app/model/Band.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pouzza.model.Band', {
    extend: 'Ext.data.Model',
    alias: 'model.Band',
    config: {
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'sort',
                type: 'string'
            },
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'venue_id',
                type: 'int'
            },
            {
                name: 'date',
                type: 'string'
            },
            {
                name: 'time',
                type: 'string'
            }
        ],
        hasOne: {
            associationKey: 'venue_id',
            model: 'Pouzza.model.Venue',
            getterName: 'getVenue',
            setterName: 'setVenue'
        }
    }
});