/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',
    config: {
        routes: {
            'item/:index': 'viewItem'
        },

        refs: {
            navView: 'navview'
        },

        control: {
            "#list": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        this.createDetailsView(record.get('name'));

        // Uncomment this line to redirect the url
        //this.redirectTo('item/' + (index + 1));
    },

    createDetailsView: function(item) {
        var details = Ext.create('MyApp.view.DetailsView', {
            title: item
        });

        this.getNavView().push(details);
    },

    viewItem: function(index) {
        var store = Ext.getStore('MyArrayStore'),
            record = store.getAt(index - 1);

        if (record) {
            this.getNavView().reset();

            this.createDetailsView(record.get('name'));   
        }
    }

});