/*
 * File: app/view/Navigation.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pouzza.view.Navigation', {
    extend: 'Ext.navigation.View',
    alias: 'widget.Navigation',

    config: {
        id: 'Navigation',
        ui: '',
        scrollable: '{"direction":"vertical"}',
        layout: {
            animation: 'slide',
            type: 'card'
        },
        navigationBar: {
            id: 'MainNavigationBar',
            items: [
                {
                    xtype: 'button',
                    id: 'ScheduleButton',
                    margin: '',
                    style: '',
                    iconCls: 'time',
                    iconMask: true,
                    align: 'right'
                }
            ]
        },
        items: [
            {
                xtype: 'panel',
                id: 'ScheduleSelection',
                padding: 10,
                title: 'Pouzza Fest',
                items: [
                    {
                        xtype: 'container',
                        height: 30,
                        html: 'View schedule by:',
                        id: 'ScheduleCaption'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        id: 'BandsButton',
                        style: 'border-bottom-left-radius:0px;border-bottom-right-radius:0px',
                        text: 'Bands'
                    },
                    {
                        xtype: 'button',
                        height: 44,
                        id: 'VenuesButton',
                        style: 'border-radius:0px;',
                        text: 'Venues'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        id: 'DatesButton',
                        style: 'border-top-left-radius:0px;border-top-right-radius:0px;',
                        text: 'Dates'
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'BandList',
                itemTpl: [
                    '{name}'
                ],
                store: 'Bands',
                grouped: true,
                title: 'Bands',
                indexBar: true
            }
        ]
    }

});