/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.controller.MyController', {
    extend: 'Ext.app.Controller',
    config: {
        control: {
            "#procesosList": {
                itemtap: 'onListpanelTap'
            },
            "#nouProces": {
                tap: 'onNouprocesTap'
            },
            "#torna": {
                tap: 'onTornaTap'
            },
            "#logout": {
                tap: 'onLogoutTap'
            }
        }
    },

    onListpanelTap: function(dataview, index, target, record, e, options) {
        Ext.getCmp('loggedInUserName').setTitle("Procés "+record.get('nom'));
        var detall = Ext.getCmp('detailPanel');
        Ext.getCmp('mainPanel').animateTo('left');
        Ext.getCmp('listPanel').setHidden(true);
        Ext.getCmp('usuariPanel').setHidden(true);
        Ext.getCmp('torna').setHidden(false);

        if (detall) {
            detall.setData(record.data);
            Ext.getCmp('finestra').setActiveItem(detall);
        } else {
            Ext.getCmp('finestra').setActiveItem({
                xclass: 'PFC.view.detailPanel'
            });
        }
        Ext.getCmp('detailPanel').setData(record.data);
        /*
        Ext.getCmp('mainPanel').push({
        xtype: 'detailpanel',
        data: record.getData()
        });
        */
    },

    onNouprocesTap: function(button, e, options) {
        /*
        Ext.getCmp('mainPanel').push({
        xtype: 'addprocesform'
        });
        */
        var afegirProces = Ext.getCmp('addprocesform');
        Ext.getCmp('mainPanel').animateTo('left');
        Ext.getCmp('listPanel').setHidden(true);
        Ext.getCmp('usuariPanel').setHidden(true);
        Ext.getCmp('torna').setHidden(false);
        Ext.getCmp('loggedInUserName').setTitle("Nou procés");

        if (afegirProces) {
            Ext.getCmp('finestra').setActiveItem(afegirProces);
        } else {
            Ext.getCmp('finestra').setActiveItem({
                xclass: 'PFC.view.addProcesForm'
            });
        }
    },

    onTornaTap: function(button, e, options) {
        Ext.getCmp('mainPanel').animateTo('right');
        Ext.getCmp('listPanel').setHidden(false);
        Ext.getCmp('usuariPanel').setHidden(false);
        Ext.getCmp('torna').setHidden(true);
        Ext.getCmp('loggedInUserName').setTitle("Processos de treball");

        Ext.getCmp('finestra').removeAt(2);
    },

    onLogoutTap: function(button, e, options) {
        Ext.getCmp('loggedInUserName').setTitle("");
        var top = Ext.getCmp('viewport');
        top.down('#loginForm').reset();
        top.down('#procesosList').deselectAll();
        top.setActiveItem(0);
    }

});