/*
 * File: app/view/ListPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.view.ListPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.listpanel',

    config: {
        id: 'listPanel',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                itemId: 'procesosList',
                itemTpl: [
                    '<div class="nom">{nom}</div>'
                ],
                store: 'procesJson',
                onItemDisclosure: false
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: 'barraEditor',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'nouProces',
                        ui: 'action-round',
                        text: 'Nou procés',
                        flex: 1
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onNouProcesTap',
                event: 'tap',
                delegate: '#nouProces'
            }
        ]
    },

    onNouProcesTap: function(button, e, options) {
        //button.up('#mainPanel').setActiveItem(0);
        button.up('#mainPanel').push({
            xtype: 'addprocesform',
            title: 'Afegir procés'
        });
    }

});