/*
 * File: app/view/mainPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.view.mainPanel', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainpanel',
    requires: [
        'PFC.view.usuariPanel'
    ],

    config: {
        defaultBackButtonText: 'Torna',
        layout: {
            animation: 'slide',
            type: 'card'
        },
        navigationBar: {
            itemId: 'loggedInUserName',
            items: [
                {
                    xtype: 'button',
                    itemId: 'logout',
                    ui: 'action',
                    text: 'Sortir',
                    align: 'left'
                }
            ]
        },
        items: [
            {
                xtype: 'usuaripanel',
                itemId: 'usuariPanel'
            }
        ],
        listeners: [
            {
                fn: 'onLogoutTap',
                event: 'tap',
                delegate: '#logout'
            }
        ]
    },

    onLogoutTap: function(button, e, options) {
        var top = button.up('viewport');
        top.down('#loginForm').reset();
        top.down('#procesosList').deselectAll();
        top.setActiveItem(0);
    }

});