/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Pouzza.controller.MainController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.MainController',
    config: {
        refs: {
            Navigation: '#Navigation',
            BandsButton: '#BandsButton',
            BandList: '#BandList'
        },

        control: {
            "BandsButton": {
                tap: 'onBandButtonTap'
            }
        }
    },

    onBandButtonTap: function(button, e, options) {

        //this.getNavigation().push(this.getBandList());

        alert('This is nav: ' + this.getNavigation());
        alert('This is bands: ' + this.getBandList());
    },

    init: function(application) {

    }

});