/*
 * File: app/view/mainPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.view.mainPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mainpanel',
    requires: [
        'PFC.view.ListPanel',
        'PFC.view.AddProcesForm',
        'PFC.view.usuariPanel'
    ],

    config: {
        layout: {
            animation: 'slide',
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'component',
                        html: '[email@example.com]',
                        itemId: 'loggedInUserName',
                        style: 'color:#FFF; padding:0 .5em; font-size: 0.8em;',
                        flex: 1
                    },
                    {
                        xtype: 'button',
                        itemId: 'logout',
                        text: 'Sortir'
                    }
                ]
            },
            {
                xtype: 'listpanel',
                itemId: 'listPanel'
            },
            {
                xtype: 'addprocesform',
                itemId: 'afegirProcesForm'
            },
            {
                xtype: 'usuaripanel',
                id: '',
                itemId: 'usuariPanel'
            }
        ],
        listeners: [
            {
                fn: 'onLogoutTap',
                event: 'tap',
                delegate: '#logout'
            }
        ]
    },

    onLogoutTap: function(button, e, options) {
        var top = button.up('Viewport');
        top.down('#loginForm').reset();
        top.setActiveItem(0);
    }

});