/*
 * File: app/view/usuariPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PFC.view.usuariPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.usuaripanel',
    requires: [
        'PFC.view.etiquetes'
    ],

    config: {
        id: 'usuariPanel',
        modal: false,
        items: [
            {
                xtype: 'container',
                layout: {
                    type: 'vbox'
                },
                title: 'Processos',
                items: [
                    {
                        xtype: 'etiquetes',
                        height: 100
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'fit'
                },
                title: 'Cerca',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'searchfield',
                                label: 'Proces:'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Filtre',
                items: [
                    {
                        xtype: 'selectfield',
                        id: 'filtre1',
                        label: 'Filtre 1',
                        value: 'id',
                        store: 'etiquetaJson'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Filtre 2'
                    }
                ]
            }
        ]
    }

});